config/routes.rb
Rails.application.routes.draw do

  root 'topics#index'

  resources :topics do
    member do
      post 'upvote'
    end
   member do
      post 'downvote'
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to topics_url
    else
      render 'new'
    end
  end

  def upvote
    @topic= Topic.find(params[:id])
    if @topic.vote == nil

      @topic.vote = 0

    end
    @topic.vote += 1
    @topic.save
    redirect_to root_path
    flash[:notice] = "Vote Added"
  end

  def downvote
    @topic= Topic.find(params[:id])
    if @topic.vote == nil

      @topic.vote = 0

    end
    @topic.vote -= 1
    @topic.save
    redirect_to root_path
    flash[:notice] = "Vote Subtracted"
  end


  private

    def topic_params
      params.require(:topic).permit(:resolution)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoteVote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%=stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!---alerts-->
    <% if flash[:error] || flash[:notice] %>
      <% if flash[:error] %>
        <div class="alert alert-danger" role="alert">
          <%=flash[:error]  %>
        </div>
      <% else %>
        <div class="alert alert-success" role="alert">
          <%=flash[:notice]  %>
        </div>
      <% end %>
      <% end %>

  <!--/end alerts-->

  <%= yield %>

</body>
</html>

app/views/topics/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
    <br>
    <br>
      <%=link_to "New Resolution",new_topic_path, class:"btn btn-default btn-lg pull-right" %>

      <h1>2016 Resolutions</h1>
      <p>What do you want to accomplish?</p>

      <hr>

      <ul>
      <% @topics.each do |topic| %>
        <li>
          <h3>
          <%= topic.resolution %>
        </h3>
          <span class="badge label-success">UPVOTES: <%= topic.vote %></span>
                  <label class="label label-warning">
            <%=topic.updated_at.to_formatted_s(:short)%>
          </label>


          

          
          <%#= link_to "Vote", :controller => :topics_controller, :method => :post %>
          <br>

          <%= link_to "Vote Up", upvote_topic_path(topic), class:"label label-success", :method => :post %>
          <%= link_to "Vote Down", downvote_topic_path(topic), class:"label label-danger", :method => :post %>
        </li>
      <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
    <br>
    <br>
    <br>
    <h1>Enter your resolution below:</h1>
    <br>
<%= form_for(@topic) do |f| %>
  <%= f.label "Enter resolution" %>
  <%= f.text_field :resolution %>
  <%= f.submit "Submit" %>
<% end %>
      
    </div>
  </div>
</div>